### ISSUE TITLE
SPM for GeniusScan SDK

### ISSUE THREAD

**Issue by rohdester** [thegrizzlylabs/geniusscan-sdk-spm#1]
Hi there,

I am evaluating GeniusScan for iOS at the moment, and stumbled upon this repo.
Does this repo mean, that I can use SPM for the GeniusScan SDK instead of manually integrating the xcframework and CocoaPod?

**Comment by bvirlet** [comment]
Yes. It's still in beta support but Genius Scan is already using this to integrate the SDK in itself :)

**Comment by rohdester** [comment]
That is so great! Thanks 👍

**Comment by bvirlet** [comment]
Closing this issue: the SPM support is official.
