### ISSUE TITLE
Release plan for tags > 4.5.0

### ISSUE THREAD

**Issue by waterskier2007** [thegrizzlylabs/geniusscan-sdk-spm#3]
I notice that there are tags all the way up to 4.10.1 but the latest "release" version is 4.5.0. Is there a plan to "release" future versions, or should consumers just use tags a pseudo-releases?

**Comment by bvirlet** [comment]
I wonder why there was a GitHub release only for version 4.5.0. I have removed it as this needed to be clarified.

Please rely on tags as they are created for every new official release of the SDK.

You can find the official changelog for each release here: https://geniusscansdk.com/docs/changelog/.
