### ISSUE TITLE
Bump SDK Apple Swift version to 5.9

### ISSUE THREAD

**Issue by piotrekjeremicz** [thegrizzlylabs/geniusscan-sdk-spm#5]
Hi,

Today I found a problem with `GSSDKScanFlow` import. I am getting an error that informs about to hight toolchain version. The message is presented on `import GSSDKScanFlow` line.

> Failed to build module 'GSSDKScanFlow'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.8.1 (swiftlang-5.8.0.124.5 clang-1403.0.22.11.100)', while this compiler is 'Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)'). Please select a toolchain which matches the SDK.

Currently, I am using **macOS** Sonoma and **Xcode 15.0**. **Genius Scan** is added to the project via **Swift Package Manager**.

Is it possible to build a framework with latest Swift toolchain? I will be glad for the answer.

**Comment by bvirlet** [comment]
Hi @piotrekjeremicz, I'm looking into this.

**Comment by piotrekjeremicz** [comment]
Thank you @bvirlet! Waiting for some results. 😊

**Comment by bvirlet** [comment]
Hi @piotrekjeremicz, just to confirm, you're pulling the latest version of the SDK?

**Comment by bvirlet** [comment]
Hi @piotrekjeremicz,

I was able to reproduce the problem in the demo project, but I had two errors:

<img width="913" alt="image" src="https://github.com/thegrizzlylabs/geniusscan-sdk-spm/assets/792706/b083f25a-14f6-4d28-bb5d-756d5f3f2850">

As soon as I added the GSSDKOCR framework as a dependency of the project (see below), the error disappeared:

<img width="889" alt="image" src="https://github.com/thegrizzlylabs/geniusscan-sdk-spm/assets/792706/40f9b770-2e12-499f-b95c-90c472e26342">

Can you let me know if it helps?

For the record:

- The SDK is built with the flag `BUILD_LIBRARY_FOR_DISTRIBUTION`, which ensures forward compatibility (the SDK is provided with the `.swiftinterface` files, ensuring compatibility with future Swift compiler versions).
- The documentation https://geniusscansdk.com/docs/v4/ios/simple-scanner-guide/ is incomplete, as `GSKOCR` is now required as a dependency of `GSKScanFlow` (the scan flow supports OCR).

**Comment by bvirlet** [comment]
Hi @piotrekjeremicz. Have you been able to verify the fix?

**Comment by piotrekjeremicz** [comment]
Hi @bvirlet . I apologize very much for the delay in replying. I have added `GSSDKOCR` library to the frameworks list and it seems to work.

I will confirm it till the end of the week. My goal is Genius Scan implementation in SwiftUI environment.

**Comment by bvirlet** [comment]
I will mark this as closed for now. Please reopen if the issue persists.
